[package]
name = "ac"
version = "0.3.0"
authors = ["Andrew Schneider <andjschneider@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
colored = "2"
git-url-parse = "0.3.1"
thiserror = "1.0"
walkdir = "2"
